#if 0

#include <iostream>

class MyClass {
public:
    // Default constructor (generated by the compiler)
    MyClass() = default;

    // Copy constructor (generated by the compiler)
    MyClass(const MyClass&) = default;

    // Destructor (generated by the compiler)
    ~MyClass() = default;

     MyClass(const NonCopyable&) = delete;
    // Deleted copy assignment operator
    MyClass& operator=(const MyClass&) = delete;
};

int main() {
    MyClass obj; // Calls the default constructor
    return 0;
}


#endif